name: Linux Build

on:
  push:
    branches: [main, experimental]
  pull_request:
    branches: [main, experimental]

  workflow_dispatch:

jobs:
   buildLinux:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      # Runs a set of commands using the runners shell
      - name: Installing LibVLC
        run: |
          sudo apt-get install libvlc-dev libvlccore-dev
      - name: Installing/Updating libraries
        run: haxe -cp commandline -D analyzer-optimize --run Main setup -s
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build Project.xml linux --app-version="4.0.0-${{ github.run_id}}"
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4
        with:
          name: Astro Engine
          path: export/release/linux/bin
